id: P004289
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:07:54.660639
source_metadata:
  id: bdr:W26075
  title: རྒྱལ་བ་དགེ་འདུན་རྒྱ་མཚོའི་རྣམ་ཐར
  author: ''
  volumes:
    26303a3aab9f4123986061b29753bfd1:
      image_group_id: I1KG1466
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
